app.url: https://orgarif.mlorber.net
#---------------------------------------------------------------------------
database:
  host: ${POSTGRESQL_ADDON_HOST}
  port: ${POSTGRESQL_ADDON_PORT}
  name: ${POSTGRESQL_ADDON_DB}
  user: ${POSTGRESQL_ADDON_USER}
  password: ${POSTGRESQL_ADDON_PASSWORD}
  protocol: jdbc:postgresql
server.forward-headers-strategy: framework
#---------------------------------------------------------------------------
assets:
  useBuildFiles: true
  webpackDevPort:
  webpackDevHost:
#---------------------------------------------------------------------------
mailjet:
  apiKey:
  secretKey:
#---------------------------------------------------------------------------
sigerUrl: https://siger.iledefrance.fr
#---------------------------------------------------------------------------
