spring:
  main.banner-mode: off
  jooq.sql-dialect: Postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.user}
    password: ${database.password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
  error.whitelabel.enabled: true
devLogMail: mathieu.lorber+log-orgarif@gmail.com
#---------------------------------------------------------------------------
reverseProxy: false
#---------------------------------------------------------------------------
assets.webpackDevHost:
#---------------------------------------------------------------------------
#segment.client.token:
#---------------------------------------------------------------------------
mailjet.url: https://api.mailjet.com/v3.1/send
#---------------------------------------------------------------------------
developerMail:
#---------------------------------------------------------------------------