app.url: https://orgarif.mlorber.net
logging.config: classpath:logback-prod.xml
#---------------------------------------------------------------------------
database:
  host: ${POSTGRESQL_ADDON_HOST}
  port: ${POSTGRESQL_ADDON_PORT}
  name: ${POSTGRESQL_ADDON_DB}
  user: ${POSTGRESQL_ADDON_USER}
  password: ${POSTGRESQL_ADDON_PASSWORD}
spring:
  datasource:
    tomcat:
      initialSize: 5
      minIdle: 5
      maxIdle: 10
      maxActive: 10
server.forward-headers-strategy: framework
#---------------------------------------------------------------------------
assets:
  useBuildFiles: true
  browserWebpackDevHost:
  serverWebpackDevHost:
#---------------------------------------------------------------------------
mailjet:
  api-key:
  secret-key:
#---------------------------------------------------------------------------
intercom.secretKey:
#---------------------------------------------------------------------------
injectFakeData: false
doSynchronizeElus: true
elusSynchronizationUrl: https://siger.mlorber.net/api/publicdata/v2/elus
