# TODO[config] no / in urls end ?
# configuration validation
app.url: http://devorgarif:8300
#---------------------------------------------------------------------------
server.port: 8300
database:
  host: localhost
  port: 5432
  name: orgarif
  user: ${USER}
  password:
#---------------------------------------------------------------------------
assets:
  useBuildFiles: false
  browserWebpackDevHost: http://localhost:3300
  serverWebpackDevHost: http://localhost:3300
#---------------------------------------------------------------------------
mailjet:
  api-key:
  secret-key:
#---------------------------------------------------------------------------
injectFakeData: true
doSynchronizeElus: true
sigerUrl: http://127.0.0.1:8080/
