app.url:
#---------------------------------------------------------------------------
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
database:
  host:
  port: 0
  name: orgarif
  user: test
  password: test
  protocol: jdbc:tc:postgresql:15
#---------------------------------------------------------------------------
assets:
  useBuildFiles: false
  webpackDevPort:
  webpackDevHost:
#---------------------------------------------------------------------------
mailjet:
  apiKey:
  secretKey:
#---------------------------------------------------------------------------
