# TODO[tmpl][config] no / in urls end ?
# configuration validation
app.url: http://devorgarif:8200
#---------------------------------------------------------------------------
insertInitialData: true
#---------------------------------------------------------------------------
server.port: 8200
database:
  host: localhost
  port: 5432
  name: orgarif
  user: ${USER}
  password:
#---------------------------------------------------------------------------
assets:
  useBuildFiles: false
  webpackDevPort: 3200
  webpackDevHost: localhost
#---------------------------------------------------------------------------
mailjet:
  api-key:
  secret-key:
#---------------------------------------------------------------------------
<<<<<<< HEAD
elusSynchronizationUrl: http://127.0.0.1:8080/api/publicdata/v2/elus
remote-endpoint:
=======
remote-controller:
>>>>>>> template
  expected-secu: remote-secu
#---------------------------------------------------------------------------
