datasource:
  user: mlo
  password:
#---------------------------------------------------------------------------
#logging.config: classpath:logback-mlo.xml
#---------------------------------------------------------------------------
developerMail: mp.lorber@gmail.com
#---------------------------------------------------------------------------
