app.url: https://orgarif-staging.mlorber.net
#---------------------------------------------------------------------------
database:
  host: ${POSTGRESQL_ADDON_HOST}
  port: ${POSTGRESQL_ADDON_PORT}
  name: ${POSTGRESQL_ADDON_DB}
  user: ${POSTGRESQL_ADDON_USER}
  password: ${POSTGRESQL_ADDON_PASSWORD}
spring:
  datasource:
    tomcat:
      initialSize: 1
      minIdle: 1
      maxIdle: 1
      maxActive: 1
server.forward-headers-strategy: framework
#---------------------------------------------------------------------------
assets:
  useBuildFiles: true
  browserWebpackDevHost:
  serverWebpackDevHost:
#---------------------------------------------------------------------------
mailjet:
  url: https://api.mailjet.com/v3.1/send
  api-key:
  secret-key:
#---------------------------------------------------------------------------
injectFakeData: false
doSynchronizeElus: true
elusSynchronizationUrl: https://siger.mlorber.net/api/publicdata/v2/elus
