# TODO[config] no / in urls end ?
# configuration validation
app.url: http://devorgarif:8300
#---------------------------------------------------------------------------
insertInitialData: true
#---------------------------------------------------------------------------
server.port: 8300
database:
  host: localhost
  port: 5432
  name: orgarif
  user: ${USER}
  password:
#---------------------------------------------------------------------------
assets:
  useBuildFiles: false
  webpackDevPort: 3300
  webpackDevHost: localhost
#---------------------------------------------------------------------------
mailjet:
  api-key:
  secret-key:
#---------------------------------------------------------------------------
elusSynchronizationUrl: http://127.0.0.1:8080/api/publicdata/v2/elus
remote-endpoint:
  expected-secu: remote-secu
#---------------------------------------------------------------------------
