#env=test
app.url:
#---------------------------------------------------------------------------
injectFakeData: false
#---------------------------------------------------------------------------
database:
  host: localhost
  port: 5432
  name: orgarif-test
  user: mlo
  password:
#---------------------------------------------------------------------------
assets.useBuildFiles: false
#---------------------------------------------------------------------------
mailjet:
  url:
  api-key:
  secret-key:
#---------------------------------------------------------------------------
doSynchronizeElus: false
elusSynchronizationUrl:
#---------------------------------------------------------------------------
