app.url: https://orgarif-staging.mlorber.net
#---------------------------------------------------------------------------
database:
  host: ${POSTGRESQL_ADDON_HOST}
  port: ${POSTGRESQL_ADDON_PORT}
  name: ${POSTGRESQL_ADDON_DB}
  user: ${POSTGRESQL_ADDON_USER}
  password: ${POSTGRESQL_ADDON_PASSWORD}
spring:
  datasource:
    tomcat:
      initialSize: 15
      minIdle: 10
      maxIdle: 15
      maxActive: 20
server.forward-headers-strategy: framework
#---------------------------------------------------------------------------
assets:
  useBuildFiles: true
  webpackDevPort:
  webpackDevHost:
#---------------------------------------------------------------------------
mailjet:
  url: https://api.mailjet.com/v3.1/send
  api-key:
  secret-key:
#---------------------------------------------------------------------------
remote-controller:
  expected-secu: ${REMOTE_CONTROLLER_EXPECTED_SECU}
#---------------------------------------------------------------------------
