database:
  host: orgarif-psql
  user: docker-psql-user
  password: docker-psql-password
# TODO param docker compose
mail:
  devDestination: mp.lorber+log-orgarif@gmail.com
pgquarrel:
assets:
  webpackDevPort: 3300
  webpackDevHost: orgarif-client
