app.url:
#---------------------------------------------------------------------------
database:
  host: localhost
  port: 5432
  name: orgarif-test
  user: mlo
  password:
#---------------------------------------------------------------------------
assets:
  useBuildFiles: false
  webpackDevPort:
  webpackDevHost:
#---------------------------------------------------------------------------
mailjet:
  api-key:
  secret-key:
#---------------------------------------------------------------------------
sigerUrl:
remote-controller:
  expected-secu: remote-secu
#---------------------------------------------------------------------------
