database:
  host: orgarif-psql
  user: docker-psql-user
  password: docker-psql-password
# TODO[tmpl] param docker compose
mail:
  devDestination:
pgquarrel:
assets:
  webpackDevPort: 3300
  webpackDevHost: orgarif-client
